### ISSUE TITLE
[help] checkpoint&log

### ISSUE THREAD

**Issue by Ezra-Yu** [zhangrui-wolf/openmmlab-competition-2021#4]
Have you train the model?
Can you attach your checkpoint and training log?

**Comment by zhangrui-wolf** [comment]
The model is now in training.

**Comment by zhangrui-wolf** [comment]
I have put the trained results in the documentation, you can click [README.md](https://github.com/zhangrui-wolf/openmmlab-competition-2021/blob/main/RepVGG/configs/repvgg/README.md) to view them.
